### ISSUE TITLE
Status of the dataset

### ISSUE THREAD

**Issue by chrzyki** [lexibank/zhoubizic#3]
Are there uncommited changes for this? It still has placeholder code etc.

**Comment by LinguList** [comment]
I have added all data now. This is a hybrid dataset where I also added phonological features.

**Comment by LinguList** [comment]
I mean: sound inventories.

**Comment by LinguList** [comment]
One second still: have to adjust contributors.md

**Comment by LinguList** [comment]
Wait: the data is not ready!

**Comment by LinguList** [comment]
We miss concepticon concept mappings.

**Comment by LinguList** [comment]
Okay, rudimentary concept mapping has been added. The concept list needs double-checking  in the future.

**Comment by LinguList** [comment]
but this can also be passed to zenodo for now, I'd say.

**Comment by chrzyki** [comment]
Thanks, I'll take care of that.

**Comment by chrzyki** [comment]
Done
